// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onaqwjaidftxwysvwdrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uYXF3amFpZGZ0eHd5c3Z3ZHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTMxODcsImV4cCI6MjA2MDM2OTE4N30.ahdLenPQ6fNiJXn1MruXZPlx6ej0sIU9dCbnmac1v0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);